### ISSUE TITLE
OrderByClause::__construct() second argument made required in 2.20.11 (BC break)

### ISSUE THREAD

**Issue by GSadee** [doctrine/doctrine2#12465]
### Bug Report

|    Q                                        |   A
|-------------------------------------------- | ------
| Version                                     | 2.20.11

#### Summary

`OrderByClause::__construct()` lost its single-argument signature in `2.20.11` (after https://github.com/doctrine/orm/pull/12437), breaking every caller that constructed the AST node directly. 

This is a BC break shipped in a patch release: `2.20.10` accepted one argument, `2.20.11` requires two.

#### Current behavior

`Doctrine\ORM\Query\AST\OrderByClause::__construct()` requires two arguments in `2.20.11`. Calling it with a single argument throws:

```
  ArgumentCountError: Too few arguments to function
  Doctrine\ORM\Query\AST\OrderByClause::__construct(),
  1 passed and exactly 2 expected
```

#### Expected behavior

Calling `new OrderByClause($items)` with a single argument should keep working in the `2.20.x` line, as it did up to and including `2.20.10`, patch releases must not break public AST/walker constructors. The second parameter should default to `true` (matching `3.6.x` #12456 behaviour).

#### How to reproduce

Example from Sylius where we encountered this problem: https://github.com/Sylius/Sylius/blob/2.3/src/Sylius/Bundle/CoreBundle/Doctrine/ORM/SqlWalker/OrderByIdentifierSqlWalker.php#L47

**Comment by greg0ire** [comment]
Cc @ofabel

**Comment by stof** [comment]
@greg0ire this issue should be closed as it is now fixed.
GitHub has not closed it automatically (based on the PR description) because the fix has not yet been merged up until the default branch of the repository, but that's fine as the default branch is not affected.
