### PR TITLE
Set default value of OrderByClause::__construct() second argument in 2.20.x

### LINKED ISSUE #12465: OrderByClause::__construct() second argument made required in 2.20.11 (BC break)
### Bug Report

|    Q                                        |   A
|-------------------------------------------- | ------
| Version                                     | 2.20.11

#### Summary

`OrderByClause::__construct()` lost its single-argument signature in `2.20.11` (after https://github.com/doctrine/orm/pull/12437), breaking every caller that constructed the AST node directly. 

This is a BC break shipped in a patch release: `2.20.10` accepted one argument, `2.20.11` requires two.

#### Current behavior

`Doctrine\ORM\Query\AST\OrderByClause::__construct()` requires two arguments in `2.20.11`. Calling it with a single argument throws:

```
  ArgumentCountError: Too few arguments to function
  Doctrine\ORM\Query\AST\OrderByClause::__construct(),
  1 passed and exactly 2 expected
```

#### Expected behavior

Calling `new OrderByClause($items)` with a single argument should keep working in the `2.20.x` line, as it did up to and including `2.20.10`, patch releases must not break public AST/walker constructors. The second parameter should default to `true` (matching `3.6.x` #12456 behaviour).

#### How to reproduce

Example from Sylius where we encountered this problem: https://github.com/Sylius/Sylius/blob/2.3/src/Sylius/Bundle/CoreBundle/Doctrine/ORM/SqlWalker/OrderByIdentifierSqlWalker.php#L47

### PR DESCRIPTION
**Pull request by GSadee**
Fixes #12465

`OrderByClause::__construct()` lost its single-argument signature in `2.20.11` (after https://github.com/doctrine/orm/pull/12437), breaking every caller that constructed the AST node directly. This is a BC break shipped in a patch release: `2.20.10` accepted one argument, `2.20.11` requires two.

The same fix was backported from the `3.6.x` branch ([#12456]), but on `3.6.x` the second parameter was added **with a default value** preserving BC, and on the `2.20.x` backport that default was dropped.

This PR re-aligns `2.20.x` with `3.6.x` by adding `= true` to the `$includeCollectionOrderByItems` parameter, same behaviour, no BC break.

### CODE REVIEW

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @GSadee !
